baseURL = 'https://overlayfactsheet.com/'
title = 'Overlay Fact Sheet'

# Site language. Available translations in the theme’s `/i18n` directory.
defaultContentLanguage = 'en'

# Renders the default content language in subdir, e.g. /. The root directory / will redirect to /
defaultContentLanguageInSubdir = 'true'

relativeURLs = 'true'

disableKinds = ['taxonomy', 'term']

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ['HTML']

[languages]
  [languages.en]
    contentDir = 'i18n/en'
    weight = 1
    [languages.en.params]
      languageName = 'english'
      languageNameShort = 'en'
  [languages.fr]
    contentDir = 'i18n/fr'
    weight = 2
    [languages.fr.params]
      languageName = 'français'
      languageNameShort = 'fr'
  [languages.ja]
    contentDir = 'i18n/ja'
    weight = 3
    [languages.ja.params]
      languageName = '日本語'
      languageNameShort = 'ja'
